url: https://benasher.co
title: Ben Asher
description: Ben Asher's personal website and blog
author:
  name: Ben Asher

timezone: America/Los_Angeles

social:
  name: Ben Asher
  links:
    - https://mastodon.social/@benasher44

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: node_modules

permalink: /:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image:
        path: /img/logo.png
        width: 1000
        height: 1000

exclude:
  - Makefile
  - vendor
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - yarn-error.log
  - yarn.lock
  - scripts
  - cached_assets.yml
  - css/includes
  - README.md
  - dangerfile.ts
  - spellcheck.json

cached_assets:
  '/css/main.css': '/css/main.css'
