name: CI

on:
  pull_request:
    branches:
      - master
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: npm install
          run: npm install
        - name: bundle install
          run: bundle install
        - name: Danger
          env:
            DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          run: bundle exec Danger
        - name: build
          run: make
      deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - uses: actions/checkout@v1
        - name: install awscli
          run: python3 -m pip install -r requirements.txt
        - name: build
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: make deploy
