name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Enable corepack
        run: corepack enable
      - name: Install deps
        run: corepack yarn install --immutable
      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: corepack yarn danger ci
      - name: build
        run: corepack yarn build