name: Push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install bundler
        run: gem install bundler
      - name: Cache bundle
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ruby-bundle-${{ hashFiles('Gemfile.lock') }}
      - name: bundle install
        run: bundle install --path=vendor/bundle
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Yarn
        run: yarn workspace focus --production
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_CF_DISTRIBUTION_ID }}
          AWS_DEFAULT_REGION: us-west-2
        run: make deploy
